version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: client
    image: parkingmanager/client:reactjs
    depends_on:
      - api
    restart: always
    networks:
      - app
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    image: parkingmanager/api:nestjs9
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app
  database:
    image: postgres
    container_name: database
    restart: always
    networks:
      - app
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: true
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${DATABASE_HOST}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USERNAME}",
          "-d",
          "${DATABASE_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 50

networks:
  app:
