version: "3.8"
services:
  client:
    command: npm run dev --prefix apps/client
    user: "0:0"
    volumes:
      - ./apps/client:/usr/src/apps/client
  api:
    command: npm run dev --prefix apps/api 
    user: "0:0"
    volumes:
      - ./apps/api:/usr/src/apps/api
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 5430:8080
    networks:
      - app